import 'package:flutter/material.dart';
import '../app/core/data/repository.dart';
import '../app/core/models/todo_item.dart';

class TodoScreen extends StatefulWidget {
  final Repository repository; // accept Repository object
  const TodoScreen({super.key, required this.repository}); // constructor

  @override
  State<TodoScreen> createState() => _TodoScreenState(); // create state
}

class _TodoScreenState extends State<TodoScreen> {
  late Future<List<TodoItem>>
      _todosFuture; // todo List - async Future object (so it can be fetched when screen loads)

  @override
  void initState() {
    super.initState();
    // fetch todos once when screen loads
    _todosFuture = widget.repository.fetchTodos();
  }

// generated by ChatGPT - just a temporary screen UI so I can see todo items
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('To-Do List')),
      body: FutureBuilder<List<TodoItem>>(
        future: _todosFuture,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator());
          } else if (snapshot.hasError) {
            return Center(child: Text('Error: ${snapshot.error}'));
          } else if (!snapshot.hasData || snapshot.data!.isEmpty) {
            return const Center(child: Text('No todos found'));
          } else {
            final todos = snapshot.data!;
            return ListView.builder(
              itemCount: todos.length,
              itemBuilder: (context, index) {
                final todo = todos[index];
                return ListTile(
                  title: Text(todo.text),
                  trailing: Icon(
                    todo.completed
                        ? Icons.check_circle
                        : Icons.radio_button_unchecked,
                    color: todo.completed ? Colors.green : Colors.grey,
                  ),
                );
              },
            );
          }
        },
      ),
    );
  }
}
