// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDSHOGH5KYKDEgUqhEPxRHv_PcVBYlIYw',
    appId: '1:946222680648:web:2519f292a88276272c267d',
    messagingSenderId: '946222680648',
    projectId: 'air-quality-demo-82f65',
    authDomain: 'air-quality-demo-82f65.firebaseapp.com',
    storageBucket: 'air-quality-demo-82f65.firebasestorage.app',
    measurementId: 'G-6WH51S67RX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHoF2-v_lFn9EfH5LHm6QNQc4unP_LN50',
    appId: '1:946222680648:android:3ef4c7594d08f5a32c267d',
    messagingSenderId: '946222680648',
    projectId: 'air-quality-demo-82f65',
    storageBucket: 'air-quality-demo-82f65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6gtGjpJ9YKeSGdayBbv7TRWBXFy6uOGg',
    appId: '1:946222680648:ios:2d731460bb442b952c267d',
    messagingSenderId: '946222680648',
    projectId: 'air-quality-demo-82f65',
    storageBucket: 'air-quality-demo-82f65.firebasestorage.app',
    iosBundleId: 'com.example.airQualityAppDemo',
  );

}